### ISSUE TITLE
Spawning Player Spawn and Ragdoll Spawn do nothing

### ISSUE THREAD

**Issue by Storungsucher** [Michal78900/MapEditorReborn#16]
Spawning a Player Spawn doesn't do anything also don't get saved in the file

**Comment by Michal78900** [comment]
Cannot replicate the issue.

**Comment by Storungsucher** [comment]
Than upload the version where it's working idiot

**Comment by NaoUnderscore** [comment]
Opena a fucking PR instead of blaming people for their work.
Fucking asshole, we're not paid to work for you. If you're having a skill issue, try to be more intelligent and shut the fuck up the next time.

**Comment by Michal78900** [comment]
Okay, so the version that is on EXILED discord in #testing-releases should work. This was a last version that I released for EXILED 4.0.0. Most of stuff should be working, but if they don't, most if not all issues were fixed in the MER for EXILED 5.0.0 which I'm currently working on.

From my testing of the older version it seems that PlayerSpawnPoint works, ragdoll throws error for some reason.

I am unable to "upload the version where it's working" as it won't work on EXILED 4.2.3. It requires EXILED 5.0.0 which was not released for now.

I would like to inform you, that insulting devs for no reason is a bad habit and most of them would ignore you at that point.
Please provide more info on how you cause an error to happen next time.
