### ISSUE TITLE
Suggestion for PlayerSpawnPoint

### ISSUE THREAD

**Issue by DentyTxR** [Michal78900/MapEditorReborn#3]
It would be pretty cool to have multiple PlayerSpawnPoints for the same class ID with a chance to spawn to one of them or another, Lets say theres 2 PlayerSpawnPoints, When a D-Class spawns in they have a 50% chance to spawn on the first PlayerSpawnPoint and 50% chance to spawn on the second PlayerSpawnPoint, Hopefully that clears up what I meant

**Comment by Michal78900** [comment]
You can have multiple custom spawn points without any issues, the problem is choosing a random one since I'm using the same method as the base-game does.

Basically if they are 2 spawn points it's 50/50

If 5 it's 20% and so on.

I don't want to patch original base-game method, because if I make a mistake in it, no one will be able to spawn and entire Northwood and EXILED squad will come to my house and burn it.
